// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: message.proto

#include "message.pb.h"
#include "message.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace CacheService {

static const char* CacheRequest_method_names[] = {
  "/CacheService.CacheRequest/SendMessage",
};

std::unique_ptr< CacheRequest::Stub> CacheRequest::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< CacheRequest::Stub> stub(new CacheRequest::Stub(channel));
  return stub;
}

CacheRequest::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_SendMessage_(CacheRequest_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status CacheRequest::Stub::SendMessage(::grpc::ClientContext* context, const ::CacheService::CacheMsgRequest& request, ::CacheService::CacheMsgReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SendMessage_, context, request, response);
}

void CacheRequest::Stub::experimental_async::SendMessage(::grpc::ClientContext* context, const ::CacheService::CacheMsgRequest* request, ::CacheService::CacheMsgReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendMessage_, context, request, response, std::move(f));
}

void CacheRequest::Stub::experimental_async::SendMessage(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::CacheService::CacheMsgReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendMessage_, context, request, response, std::move(f));
}

void CacheRequest::Stub::experimental_async::SendMessage(::grpc::ClientContext* context, const ::CacheService::CacheMsgRequest* request, ::CacheService::CacheMsgReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendMessage_, context, request, response, reactor);
}

void CacheRequest::Stub::experimental_async::SendMessage(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::CacheService::CacheMsgReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendMessage_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::CacheService::CacheMsgReply>* CacheRequest::Stub::AsyncSendMessageRaw(::grpc::ClientContext* context, const ::CacheService::CacheMsgRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::CacheService::CacheMsgReply>::Create(channel_.get(), cq, rpcmethod_SendMessage_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::CacheService::CacheMsgReply>* CacheRequest::Stub::PrepareAsyncSendMessageRaw(::grpc::ClientContext* context, const ::CacheService::CacheMsgRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::CacheService::CacheMsgReply>::Create(channel_.get(), cq, rpcmethod_SendMessage_, context, request, false);
}

CacheRequest::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CacheRequest_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CacheRequest::Service, ::CacheService::CacheMsgRequest, ::CacheService::CacheMsgReply>(
          std::mem_fn(&CacheRequest::Service::SendMessage), this)));
}

CacheRequest::Service::~Service() {
}

::grpc::Status CacheRequest::Service::SendMessage(::grpc::ServerContext* context, const ::CacheService::CacheMsgRequest* request, ::CacheService::CacheMsgReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace CacheService

